# llvm-link-14
# Autogenerated from man page /usr/share/man/man1/llvm-link-14.1.gz
complete -c llvm-link-14 -s f -d 'Enable binary output on terminals'
complete -c llvm-link-14 -s o -d 'Specify the output file name'
complete -c llvm-link-14 -s S -d 'Write output in LLVM intermediate language (instead of bitcode)'
complete -c llvm-link-14 -s d -d 'If specified, llvm-link prints a human-readable version of the output bitcode…'
complete -c llvm-link-14 -o help -d 'Print a summary of command line options'
complete -c llvm-link-14 -s v -d 'Verbose mode.   Print information about what llvm-link is doing'

