# llvm-strings-14
# Autogenerated from man page /usr/share/man/man1/llvm-strings-14.1.gz
complete -c llvm-strings-14 -l all -s a -d 'Silently ignored.  Present for GNU strings compatibility'
complete -c llvm-strings-14 -l bytes -s n -d 'Set the minimum number of printable ASCII characters required for a sequence …'
complete -c llvm-strings-14 -l help -s h -d 'Display a summary of command line options'
complete -c llvm-strings-14 -l print-file-name -s f -d 'Display the name of the containing file before each string'
complete -c llvm-strings-14 -l radix -s t -d 'Display the offset within the file of each string, before the string and usin…'
complete -c llvm-strings-14 -l version -d 'Display the version of the llvm-strings executable'

