# llvm-rtdyld-14
# Autogenerated from man page /usr/share/man/man1/llvm-rtdyld-14.1.gz
complete -c llvm-rtdyld-14 -l color
complete -c llvm-rtdyld-14 -l help -l help-hidden
complete -c llvm-rtdyld-14 -l help-list -l help-list-hidden
complete -c llvm-rtdyld-14 -l version
complete -c llvm-rtdyld-14 -l args
complete -c llvm-rtdyld-14 -l check
complete -c llvm-rtdyld-14 -l dylib
complete -c llvm-rtdyld-14 -l entry
complete -c llvm-rtdyld-14 -l mcpu -o mcpu
complete -c llvm-rtdyld-14 -l preallocate
complete -c llvm-rtdyld-14 -l show-times
complete -c llvm-rtdyld-14 -l triple -d 'Action to perform:'
complete -c llvm-rtdyld-14 -l execute
complete -c llvm-rtdyld-14 -l printline
complete -c llvm-rtdyld-14 -l printdebugline
complete -c llvm-rtdyld-14 -l printobjline -o printlineinfo
complete -c llvm-rtdyld-14 -l verify

