version: "3.6"
services:
  dev:
    build:
      context: . # Make CWD visible to building container.
      dockerfile: Dockerfile
      args:
        uid: ${UID}
        user: ${USER}
    env_file: .env
    image: unidev
    network_mode: host
    volumes:
      - ./home:/home/${USER}
      - /:/home/${USER}/host
      - ./config:/home/${USER}/.config
      - ./local:/home/${USER}/.local
      - ${HOME}/.ssh:/home/${USER}/.ssh
      - ${SSH_AUTH_SOCK_DIR}:${SSH_AUTH_SOCK_DIR}
      - /var/run/docker.sock:/var/run/docker.sock # Connect docker
