function bp-cmake
cd $HHOME/dev/bellport/build-debug \
&& cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-std=c++20 -fPIC" -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBELLPORT_LICENSE_ENABLED=OFF ../
end
