* Tasks
** TODO BBO option
  [2022-06-13 Mon]
  [[file:~/host/home/seans/dev/bellport/src/bp/apps/mstnorm/utils.hpp::if (bp::feed::kDepthOfBookLevel_Unknown != depth_of_book_) {]]

  Example feeds with BBO data:
  - totalview
  - qbbo

  Ask Pramod for a feed that produces both BBO and APU in the same data feed.

  N.b.: Integrated feeds contain just the APU.

  I should provide an option --no-apu-subscription to *explicitly* disable
  subscriptions to APU, and --bbo to produce BBO updates. By default, unless
  ~--no-apu-subscription~ is passed, I should automatically subscribe to the APU
  if the feed doesn't have a BBO of its own.
** TODO
  [2022-06-23 Thu]
  [[file:~/host/home/seans/dev/bellport/src/bp/apps/mstnorm/utils.hpp::if (bp::feed::kDepthOfBookLevel_Unknown != setup_args.depth_of_book) {]]

  BBO message code?
** TODO
  [2022-06-24 Fri]
  [[file:~/host/home/seans/dev/bellport/src/bp/apps/mstnorm/printer.cpp::bp::feed::BBOQuote bbo_quote = apu.ToBBOQuote();]]
Convert an APU into a BBO quote.
