# aclocal
# Autogenerated from man page /usr/share/man/man1/aclocal.1.gz
complete -c aclocal -l automake-acdir -d 'directory holding automake-provided m4 files'
complete -c aclocal -l system-acdir -d 'directory holding third-party system-wide files'
complete -c aclocal -l diff -d 'run COMMAND [diff -u] on M4 files that would be changed (implies --install an…'
complete -c aclocal -l dry-run -d 'pretend to, but do not actually update any file'
complete -c aclocal -l force -d 'always update output file'
complete -c aclocal -l help -d 'print this help, then exit'
complete -c aclocal -s I -d 'add directory to search list for . m4 files'
complete -c aclocal -l install -d 'copy third-party files to the first -I directory'
complete -c aclocal -l output -d 'put output in FILE (default aclocal. m4)'
complete -c aclocal -l print-ac-dir -d 'print name of directory holding system-wide third-party m4 files, then exit'
complete -c aclocal -l verbose -d 'don\'t be silent'
complete -c aclocal -l version -d 'print version number, then exit'
complete -c aclocal -s W -l warnings -d 'report the warnings falling in CATEGORY . SS "Warning categories include:"'

