# llvm-install-name-tool-14
# Autogenerated from man page /usr/share/man/man1/llvm-install-name-tool-14.1.gz
complete -c llvm-install-name-tool-14 -o add_rpath -d 'Add an rpath named <rpath> to the specified binary'
complete -c llvm-install-name-tool-14 -o change -d 'Change an install name <old_install_name> to <new_install_name> in the specif…'
complete -c llvm-install-name-tool-14 -o delete_rpath -d 'Delete an rpath named <rpath> from the specified binary'
complete -c llvm-install-name-tool-14 -o delete_all_rpaths -d 'Deletes all rpaths from the binary'
complete -c llvm-install-name-tool-14 -l help -s h -d 'Print a summary of command line options'
complete -c llvm-install-name-tool-14 -o id -d 'Change shared libraryâs identification name under LC_ID_DYLIB to <name> in …'
complete -c llvm-install-name-tool-14 -o rpath -d 'Change an rpath named <old_rpath> to <new_rpath> in the specified binary'
complete -c llvm-install-name-tool-14 -l version -s V -d 'Display the version of the llvm-install-name-tool executable'

