# editor
# Autogenerated from man page /usr/share/man/man1/editor.1.gz
complete -c editor -s h -l help -d 'display this help and exit'
complete -c editor -s V -l version -d 'output version information and exit'
complete -c editor -s E -l extended-regexp -d 'use extended regular expressions'
complete -c editor -s G -l traditional -d 'run in compatibility mode'
complete -c editor -s l -l loose-exit-status -d 'exit with 0 status even if a command fails'
complete -c editor -s p -l prompt -d 'use STRING as an interactive prompt'
complete -c editor -s r -l restricted -d 'run in restricted mode'
complete -c editor -s s -l quiet -l silent -d 'suppress diagnostics, byte counts and \'!\' prompt'
complete -c editor -s v -l verbose -d 'be verbose; equivalent to the \'H\' command'
complete -c editor -l strip-trailing-cr -d 'strip carriage returns at end of text lines'

