# llvm-mc-14
# Autogenerated from man page /usr/share/man/man1/llvm-mc-14.1.gz
complete -c llvm-mc-14 -l color
complete -c llvm-mc-14 -l help -l help-hidden
complete -c llvm-mc-14 -l help-list -l help-list-hidden
complete -c llvm-mc-14 -l version
complete -c llvm-mc-14 -s I
complete -c llvm-mc-14 -s M
complete -c llvm-mc-14 -l arch -o version -d 'Action to perform:'
complete -c llvm-mc-14 -l as-lex
complete -c llvm-mc-14 -l assemble
complete -c llvm-mc-14 -l disassemble
complete -c llvm-mc-14 -l mdis
complete -c llvm-mc-14 -l compress-debug-sections
complete -c llvm-mc-14 -l defsym
complete -c llvm-mc-14 -l fdebug-compilation-dir
complete -c llvm-mc-14 -l fdebug-prefix-map
complete -c llvm-mc-14 -l filetype
complete -c llvm-mc-14 -s g
complete -c llvm-mc-14 -l large-code-model
complete -c llvm-mc-14 -l main-file-name
complete -c llvm-mc-14 -l masm-hexfloats
complete -c llvm-mc-14 -l masm-integers
complete -c llvm-mc-14 -l mattr -o a3 -o mattr
complete -c llvm-mc-14 -l mcpu -o mcpu
complete -c llvm-mc-14 -l motorola-integers
complete -c llvm-mc-14 -s n
complete -c llvm-mc-14 -l no-exec-stack
complete -c llvm-mc-14 -s o
complete -c llvm-mc-14 -l output-asm-variant
complete -c llvm-mc-14 -l position-independent
complete -c llvm-mc-14 -l preserve-comments
complete -c llvm-mc-14 -l print-imm-hex
complete -c llvm-mc-14 -l relax-relocations
complete -c llvm-mc-14 -l save-temp-labels
complete -c llvm-mc-14 -l show-encoding
complete -c llvm-mc-14 -l show-inst
complete -c llvm-mc-14 -l show-inst-operands
complete -c llvm-mc-14 -l split-dwarf-file
complete -c llvm-mc-14 -l triple

