# llvm-dis-14
# Autogenerated from man page /usr/share/man/man1/llvm-dis-14.1.gz
complete -c llvm-dis-14 -s o -d OPTIONS
complete -c llvm-dis-14 -s f -d 'Enable binary output on terminals'
complete -c llvm-dis-14 -o help -d 'Print a summary of command line options'

