# llvm-tli-checker-14
# Autogenerated from man page /usr/share/man/man1/llvm-tli-checker-14.1.gz
complete -c llvm-tli-checker-14 -l dump-tli -d 'Print âavailableâ/ânot availableâ for each library function, accordin…'
complete -c llvm-tli-checker-14 -l help -s h -d 'Print a summary of command line options and exit'
complete -c llvm-tli-checker-14 -l libdir -d 'A base directory to prepend to each library file path'
complete -c llvm-tli-checker-14 -l report -d 'The amount of information to report'
complete -c llvm-tli-checker-14 -l separate -d 'Read and report a summary for each library file separately'
complete -c llvm-tli-checker-14 -l triple -d 'The triple to use for initializing TargetLibraryInfo'

