# llvm-size-14
# Autogenerated from man page /usr/share/man/man1/llvm-size-14.1.gz
complete -c llvm-size-14 -s A -d 'Alias for --format'
complete -c llvm-size-14 -s B -d 'Alias for --format'
complete -c llvm-size-14 -l common -d 'Print common symbols in the ELF file'
complete -c llvm-size-14 -s d -d 'Alias for --radix=\\,10\\/ . HP --format=<value> Specify output format'
complete -c llvm-size-14 -l help -d 'Display this help'
complete -c llvm-size-14 -s h -d 'Alias for --help'
complete -c llvm-size-14 -s m -d 'Alias for --format'
complete -c llvm-size-14 -s o -d 'Alias for --radix=\\,8\\/'
complete -c llvm-size-14 -l radix -d 'Print size in radix'
complete -c llvm-size-14 -l totals -d 'Print totals of all objects - Berkeley format only'
complete -c llvm-size-14 -s t -d 'Alias for --totals'
complete -c llvm-size-14 -l version -d 'Display the version'
complete -c llvm-size-14 -s x -d 'Alias for --radix=\\,16\\/ . SS "OPTIONS (Mach-O specific):" '
complete -c llvm-size-14 -l format
complete -c llvm-size-14 -l arch
complete -c llvm-size-14 -s l -d 'When format is darwin, use long format to include addresses and offsets'

