# pyenv
# Autogenerated from man page /home/seans/.pyenv/man/man1/pyenv.1
complete -c pyenv -s h -l help -d 'Show summary of options'
complete -c pyenv -s v -l version -d 'Show version of program.  COMPARISON'

