# x-terminal-emulator
# Autogenerated from man page /usr/share/man/man1/x-terminal-emulator.1.gz
complete -c x-terminal-emulator -o class
complete -c x-terminal-emulator -o k8 -d and
complete -c x-terminal-emulator -o u8 -d 'options should not be specified because they are used by koi8rxterm and uxter…'

