# bugpoint-14
# Autogenerated from man page /usr/share/man/man1/bugpoint-14.1.gz
complete -c bugpoint-14 -o find-bugs -d 'Continually randomize the specified passes and run them on the test program u…'
complete -c bugpoint-14 -o help -d 'Print a summary of command line options'

