# libpng16-config
# Autogenerated from man page /usr/share/man/man1/libpng16-config.1.gz
complete -c libpng16-config -l prefix -d 'print libpng prefix'
complete -c libpng16-config -l libdir -d 'print path to directory containing library'
complete -c libpng16-config -l libs -d 'print library linking information'
complete -c libpng16-config -l ccopts -d 'print compiler options'
complete -c libpng16-config -l cppflags -d 'print pre-processor flags'
complete -c libpng16-config -l cflags -d 'print preprocessor flags, I_opts, and compiler options'
complete -c libpng16-config -l I_opts -d 'print "-I" include options'
complete -c libpng16-config -l L_opts -d 'print linker "-L" flags for dynamic linking'
complete -c libpng16-config -l R_opts -d 'print dynamic linker "-R" or "-rpath" flags'
complete -c libpng16-config -l ldopts -d 'print linker options'
complete -c libpng16-config -l ldflags -d 'print linker flags (ldopts, L_opts, R_opts, and libs)'
complete -c libpng16-config -l static -d 'revise subsequent outputs for static linking'
complete -c libpng16-config -l help -d 'print this help and exit'
complete -c libpng16-config -l version -d 'print version information AUTHOR This manpage has been written by Junichi Uek…'

