# llvm-dwarfdump-14
# Autogenerated from man page /usr/share/man/man1/llvm-dwarfdump-14.1.gz
complete -c llvm-dwarfdump-14 -l color
complete -c llvm-dwarfdump-14 -l help -l help-hidden
complete -c llvm-dwarfdump-14 -l help-list -l help-list-hidden
complete -c llvm-dwarfdump-14 -l version
complete -c llvm-dwarfdump-14 -s a -l all
complete -c llvm-dwarfdump-14 -l apple-names
complete -c llvm-dwarfdump-14 -l apple-namespaces
complete -c llvm-dwarfdump-14 -l apple-objc
complete -c llvm-dwarfdump-14 -l apple-types
complete -c llvm-dwarfdump-14 -l debug-abbrev
complete -c llvm-dwarfdump-14 -l debug-addr
complete -c llvm-dwarfdump-14 -l debug-aranges
complete -c llvm-dwarfdump-14 -l debug-cu-index
complete -c llvm-dwarfdump-14 -l debug-frame
complete -c llvm-dwarfdump-14 -l debug-gnu-pubnames
complete -c llvm-dwarfdump-14 -l debug-gnu-pubtypes
complete -c llvm-dwarfdump-14 -l debug-info
complete -c llvm-dwarfdump-14 -l debug-line
complete -c llvm-dwarfdump-14 -l debug-line-str
complete -c llvm-dwarfdump-14 -l debug-loc
complete -c llvm-dwarfdump-14 -l debug-loclists
complete -c llvm-dwarfdump-14 -l debug-macro
complete -c llvm-dwarfdump-14 -l debug-names
complete -c llvm-dwarfdump-14 -l debug-pubnames
complete -c llvm-dwarfdump-14 -l debug-pubtypes
complete -c llvm-dwarfdump-14 -l debug-ranges
complete -c llvm-dwarfdump-14 -l debug-rnglists
complete -c llvm-dwarfdump-14 -l debug-str
complete -c llvm-dwarfdump-14 -l debug-str-offsets
complete -c llvm-dwarfdump-14 -l debug-tu-index
complete -c llvm-dwarfdump-14 -l debug-types
complete -c llvm-dwarfdump-14 -l eh-frame
complete -c llvm-dwarfdump-14 -l gdb-index
complete -c llvm-dwarfdump-14 -s F -l show-form
complete -c llvm-dwarfdump-14 -l arch
complete -c llvm-dwarfdump-14 -s c -l show-children
complete -c llvm-dwarfdump-14 -l diff
complete -c llvm-dwarfdump-14 -s f -l find
complete -c llvm-dwarfdump-14 -o name
complete -c llvm-dwarfdump-14 -s i -l ignore-case
complete -c llvm-dwarfdump-14 -l name
complete -c llvm-dwarfdump-14 -l lookup
complete -c llvm-dwarfdump-14 -s n
complete -c llvm-dwarfdump-14 -s o
complete -c llvm-dwarfdump-14 -s p -l show-parents
complete -c llvm-dwarfdump-14 -l parent-recurse-depth
complete -c llvm-dwarfdump-14 -l quiet -o verify
complete -c llvm-dwarfdump-14 -s r -l recurse-depth
complete -c llvm-dwarfdump-14 -l regex
complete -c llvm-dwarfdump-14 -l show-section-sizes
complete -c llvm-dwarfdump-14 -l statistics
complete -c llvm-dwarfdump-14 -l summarize-types
complete -c llvm-dwarfdump-14 -s u -l uuid
complete -c llvm-dwarfdump-14 -s v -l verbose
complete -c llvm-dwarfdump-14 -l verify
complete -c llvm-dwarfdump-14 -s x

