# llvm-as-14
# Autogenerated from man page /usr/share/man/man1/llvm-as-14.1.gz
complete -c llvm-as-14 -s f -d 'Enable binary output on terminals'
complete -c llvm-as-14 -o help -d 'Print a summary of command line options'
complete -c llvm-as-14 -s o -d 'Specify the output file name'

