# llvm-mc
# Autogenerated from man page /usr/share/man/man1/llvm-mc.1.gz
complete -c llvm-mc -l color
complete -c llvm-mc -l help -l help-hidden
complete -c llvm-mc -l help-list -l help-list-hidden
complete -c llvm-mc -l version
complete -c llvm-mc -s I
complete -c llvm-mc -s M
complete -c llvm-mc -l arch -o version -d 'Action to perform:'
complete -c llvm-mc -l as-lex
complete -c llvm-mc -l assemble
complete -c llvm-mc -l disassemble
complete -c llvm-mc -l mdis
complete -c llvm-mc -l compress-debug-sections
complete -c llvm-mc -l defsym
complete -c llvm-mc -l fdebug-compilation-dir
complete -c llvm-mc -l fdebug-prefix-map
complete -c llvm-mc -l filetype
complete -c llvm-mc -s g
complete -c llvm-mc -l large-code-model
complete -c llvm-mc -l main-file-name
complete -c llvm-mc -l masm-hexfloats
complete -c llvm-mc -l masm-integers
complete -c llvm-mc -l mattr -o a3 -o mattr
complete -c llvm-mc -l mcpu -o mcpu
complete -c llvm-mc -l motorola-integers
complete -c llvm-mc -s n
complete -c llvm-mc -l no-exec-stack
complete -c llvm-mc -s o
complete -c llvm-mc -l output-asm-variant
complete -c llvm-mc -l position-independent
complete -c llvm-mc -l preserve-comments
complete -c llvm-mc -l print-imm-hex
complete -c llvm-mc -l relax-relocations
complete -c llvm-mc -l save-temp-labels
complete -c llvm-mc -l show-encoding
complete -c llvm-mc -l show-inst
complete -c llvm-mc -l show-inst-operands
complete -c llvm-mc -l split-dwarf-file
complete -c llvm-mc -l triple

