# llvm-ranlib
# Autogenerated from man page /usr/share/man/man1/llvm-ranlib.1.gz
complete -c llvm-ranlib -s h -l help
complete -c llvm-ranlib -s v -l version
complete -c llvm-ranlib -s D
complete -c llvm-ranlib -s U

