# llvm-rtdyld
# Autogenerated from man page /usr/share/man/man1/llvm-rtdyld.1.gz
complete -c llvm-rtdyld -l color
complete -c llvm-rtdyld -l help -l help-hidden
complete -c llvm-rtdyld -l help-list -l help-list-hidden
complete -c llvm-rtdyld -l version
complete -c llvm-rtdyld -l args
complete -c llvm-rtdyld -l check
complete -c llvm-rtdyld -l dylib
complete -c llvm-rtdyld -l entry
complete -c llvm-rtdyld -l mcpu -o mcpu
complete -c llvm-rtdyld -l preallocate
complete -c llvm-rtdyld -l show-times
complete -c llvm-rtdyld -l triple -d 'Action to perform:'
complete -c llvm-rtdyld -l execute
complete -c llvm-rtdyld -l printline
complete -c llvm-rtdyld -l printdebugline
complete -c llvm-rtdyld -l printobjline -o printlineinfo
complete -c llvm-rtdyld -l verify

