# llvm-extract-14
# Autogenerated from man page /usr/share/man/man1/llvm-extract-14.1.gz
complete -c llvm-extract-14 -s f -d 'Enable binary output on terminals'
complete -c llvm-extract-14 -o help -d 'Print a summary of command line options'
complete -c llvm-extract-14 -s o -d 'Specify the output filename'
complete -c llvm-extract-14 -s S -d 'Write output in LLVM intermediate language (instead of bitcode).  EXIT STATUS'

