# llvm-size
# Autogenerated from man page /usr/share/man/man1/llvm-size.1.gz
complete -c llvm-size -s A -d 'Alias for --format'
complete -c llvm-size -s B -d 'Alias for --format'
complete -c llvm-size -l common -d 'Print common symbols in the ELF file'
complete -c llvm-size -s d -d 'Alias for --radix=\\,10\\/ . HP --format=<value> Specify output format'
complete -c llvm-size -l help -d 'Display this help'
complete -c llvm-size -s h -d 'Alias for --help'
complete -c llvm-size -s m -d 'Alias for --format'
complete -c llvm-size -s o -d 'Alias for --radix=\\,8\\/'
complete -c llvm-size -l radix -d 'Print size in radix'
complete -c llvm-size -l totals -d 'Print totals of all objects - Berkeley format only'
complete -c llvm-size -s t -d 'Alias for --totals'
complete -c llvm-size -l version -d 'Display the version'
complete -c llvm-size -s x -d 'Alias for --radix=\\,16\\/ . SS "OPTIONS (Mach-O specific):" '
complete -c llvm-size -l format
complete -c llvm-size -l arch
complete -c llvm-size -s l -d 'When format is darwin, use long format to include addresses and offsets'

