# llvm-ranlib-14
# Autogenerated from man page /usr/share/man/man1/llvm-ranlib-14.1.gz
complete -c llvm-ranlib-14 -s h -l help
complete -c llvm-ranlib-14 -s v -l version
complete -c llvm-ranlib-14 -s D
complete -c llvm-ranlib-14 -s U

