# aarch64-linux-gnu-dwp
# Autogenerated from man page /usr/share/man/man1/aarch64-linux-gnu-dwp.1.gz
complete -c aarch64-linux-gnu-dwp -s h -l help -d 'Print this help message'
complete -c aarch64-linux-gnu-dwp -s e -l exec -d 'Get list of dwo files from EXE (defaults output to EXE. dwp)'
complete -c aarch64-linux-gnu-dwp -s o -l output -d 'Set output dwp file name'
complete -c aarch64-linux-gnu-dwp -s v -l verbose -d 'Verbose output'
complete -c aarch64-linux-gnu-dwp -l verify-only -d 'Verify output file against exec file'
complete -c aarch64-linux-gnu-dwp -s V -l version -d 'Print version number REPORTING BUGS Report bugs to <https://sourceware'

