# llvm-dwarfdump
# Autogenerated from man page /usr/share/man/man1/llvm-dwarfdump.1.gz
complete -c llvm-dwarfdump -l color
complete -c llvm-dwarfdump -l help -l help-hidden
complete -c llvm-dwarfdump -l help-list -l help-list-hidden
complete -c llvm-dwarfdump -l version
complete -c llvm-dwarfdump -s a -l all
complete -c llvm-dwarfdump -l apple-names
complete -c llvm-dwarfdump -l apple-namespaces
complete -c llvm-dwarfdump -l apple-objc
complete -c llvm-dwarfdump -l apple-types
complete -c llvm-dwarfdump -l debug-abbrev
complete -c llvm-dwarfdump -l debug-addr
complete -c llvm-dwarfdump -l debug-aranges
complete -c llvm-dwarfdump -l debug-cu-index
complete -c llvm-dwarfdump -l debug-frame
complete -c llvm-dwarfdump -l debug-gnu-pubnames
complete -c llvm-dwarfdump -l debug-gnu-pubtypes
complete -c llvm-dwarfdump -l debug-info
complete -c llvm-dwarfdump -l debug-line
complete -c llvm-dwarfdump -l debug-line-str
complete -c llvm-dwarfdump -l debug-loc
complete -c llvm-dwarfdump -l debug-loclists
complete -c llvm-dwarfdump -l debug-macro
complete -c llvm-dwarfdump -l debug-names
complete -c llvm-dwarfdump -l debug-pubnames
complete -c llvm-dwarfdump -l debug-pubtypes
complete -c llvm-dwarfdump -l debug-ranges
complete -c llvm-dwarfdump -l debug-rnglists
complete -c llvm-dwarfdump -l debug-str
complete -c llvm-dwarfdump -l debug-str-offsets
complete -c llvm-dwarfdump -l debug-tu-index
complete -c llvm-dwarfdump -l debug-types
complete -c llvm-dwarfdump -l eh-frame
complete -c llvm-dwarfdump -l gdb-index
complete -c llvm-dwarfdump -s F -l show-form
complete -c llvm-dwarfdump -l arch
complete -c llvm-dwarfdump -s c -l show-children
complete -c llvm-dwarfdump -l diff
complete -c llvm-dwarfdump -s f -l find
complete -c llvm-dwarfdump -o name
complete -c llvm-dwarfdump -s i -l ignore-case
complete -c llvm-dwarfdump -l name
complete -c llvm-dwarfdump -l lookup
complete -c llvm-dwarfdump -s n
complete -c llvm-dwarfdump -s o
complete -c llvm-dwarfdump -s p -l show-parents
complete -c llvm-dwarfdump -l parent-recurse-depth
complete -c llvm-dwarfdump -l quiet -o verify
complete -c llvm-dwarfdump -s r -l recurse-depth
complete -c llvm-dwarfdump -l regex
complete -c llvm-dwarfdump -l show-section-sizes
complete -c llvm-dwarfdump -l statistics
complete -c llvm-dwarfdump -l summarize-types
complete -c llvm-dwarfdump -s u -l uuid
complete -c llvm-dwarfdump -s v -l verbose
complete -c llvm-dwarfdump -l verify
complete -c llvm-dwarfdump -s x

