# llvm-stress-14
# Autogenerated from man page /usr/share/man/man1/llvm-stress-14.1.gz
complete -c llvm-stress-14 -s o -d 'Specify the output filename'
complete -c llvm-stress-14 -o size -d 'Specify the size of the generated . ll file'
complete -c llvm-stress-14 -o seed -d 'Specify the seed to be used for the randomly generated instructions'

