# lxterm
# Autogenerated from man page /usr/share/man/man1/lxterm.1.gz
complete -c lxterm -o class
complete -c lxterm -o k8 -d and
complete -c lxterm -o u8 -d 'options should not be specified because they are used by koi8rxterm and uxter…'

